### PR TITLE
add doubleSpacePeriod command

### PR DESCRIPTION
**Pull request by marsch**
relates to: https://github.com/the-grid/ed/issues/170

### CODE REVIEW

**Comment by forresto** [comment]
Needs to sniff iOS, because double-space works in android and (probably) shouldn't be enabled on desktop. https://github.com/the-grid/ed/issues/109#issuecomment-210153888

**Comment by marsch** [comment]
@forresto yeah - think so too - this is just to try it out, but anyway - how would you sniff it?

**Comment by forresto** [comment]
`if ( /iPad|iPhone|iPod/.test(navigator.userAgent) ) { commands.add(iOSHacks) }` https://github.com/the-grid/ed/blob/d30e153fe5c2d1fc5b9a4adef9a16e3e636d8122/src/commands/index.js#L6

**Comment by marsch** [comment]
@forresto did :)

**Pull request merged**
