### PR TITLE
onPlaceholderCancel

### PR DESCRIPTION
**Pull request by forresto**
- Placeholder progress bar
  - `progress` 0-100 with `ed.updatePlaceholder(id, status, progress)` or `ed.setContent([{id, metadata: {status, progress}}])`
- NEW -- **X** button on the Placeholder component triggers `options.onPlaceholderCancel(id)`
  - When that is hit, `ed.getContent()` will already have removed the cancelled placeholder block
- Delete from under media block ignored

### CODE REVIEW

**Comment by JohnRandom** [comment]
@forresto I found some weirdness with this PR:
- When I start typing text, hit `Enter` and upload an image, it gets placed above the fold, even though it was inserted below the fold under what I typed in earlier.
- Once an image was uploaded above the fold, it can no longer be removed using `Backspace`, which is Ok. Of course, now we need another way to remove the image.

**Comment by forresto** [comment]
@JohnRandom both of those are 0.5.0 issues, not new here. Bumping first media above fold is by design, and control to remove media blocks is coming.

**Comment by forresto** [comment]
Though, could be easy to not bump them up.

**Comment by forresto** [comment]
@JohnRandom Poking the code some, I can't keep the same `onFileUpload(index)` option if I don't automatically bump the first one up. I'd rather keep the API as it is and see what people think about the first media getting bumped up.

**Pull request merged**
